#!/bin/bash

black-check(){
    black --check --quiet . && echo "Black Check ✅" || {
        >&2 echo "Black Check ❌"
        echo "Suggestion: Run - black ."
        echo ""
        FAILURE=1
    }
}

flake8-check() {
    flake8 && echo "Flake8 Check ✅" ||{
        >&2 echo "Flake8 Check ❌"
        echo "Suggestion: Run - flake8 ."
        echo ""
        FAILURE=1
    }
}

black-check
echo ""
flake8-check
exit $FAILURE
