# Generated by Django 3.0.6 on 2021-03-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username_or_Email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SlideShowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('image', models.ImageField(upload_to='Images/slideshow')),
                ('content', models.CharField(max_length=200, verbose_name='Enter content only upto 200 characters')),
                ('read_more', models.CharField(max_length=1000, verbose_name='Add a read more link to related article')),
            ],
        ),
    ]
