# Generated by Django 3.0.6 on 2021-04-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_login"),
        ("main_app", "0002_contact_mobile_no"),
    ]

    operations = []
