# Generated by Django 3.0.6 on 2021-03-30 14:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210330_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshowitem',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=('/Users/nikhilmankani/Downloads/Rescue/main_app/static',)), upload_to='Images/slideshow'),
        ),
    ]
