# Generated by Django 3.0.6 on 2021-04-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
