# Generated by Django 3.1.7 on 2021-04-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_register_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='about',
        ),
        migrations.RemoveField(
            model_name='register_table',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='register_table',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d'),
        ),
    ]
