# Generated by Django 3.1.7 on 2021-04-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210416_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
