# Generated by Django 3.0.6 on 2021-04-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210416_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='profile_pic',
        ),
    ]
